package org.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VetSpecialtyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetSpecialtyAllPropertiesEquals(VetSpecialty expected, VetSpecialty actual) {
        assertVetSpecialtyAutoGeneratedPropertiesEquals(expected, actual);
        assertVetSpecialtyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetSpecialtyAllUpdatablePropertiesEquals(VetSpecialty expected, VetSpecialty actual) {
        assertVetSpecialtyUpdatableFieldsEquals(expected, actual);
        assertVetSpecialtyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetSpecialtyAutoGeneratedPropertiesEquals(VetSpecialty expected, VetSpecialty actual) {
        assertThat(expected)
            .as("Verify VetSpecialty auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetSpecialtyUpdatableFieldsEquals(VetSpecialty expected, VetSpecialty actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetSpecialtyUpdatableRelationshipsEquals(VetSpecialty expected, VetSpecialty actual) {}
}
